server:
  port: 8080
shiro:
  ws:
    client:
      enable: true
      url: "ws://127.0.0.1:3001"
  task-pool:
    # 核心线程数（默认线程数）
    core-pool-size: 20
    # 缓冲队列大小
    queue-capacity: 200
    # 允许线程空闲时间（单位：默认为秒）
    keep-alive-time: 10
    # 最大线程数
    max-pool-size: 32
    # 线程池名前缀
    thread-name-prefix: "OneBotEvent-"
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  freemarker:
    check-template-location: false
  profiles:
    active: default
lomu:
  web:
    # 是否显式页面信息 true为否
    headless: true
    # 池大小
    size: 2
  bot:
    private: false